### ISSUE TITLE
Inspector displays '^show/$' as matching to request `/show/`, but frontend 404-s

### ISSUE THREAD

**Issue by lkraav** [Automattic/Rewrite-Rules-Inspector#25]
Correct matching string would actually be `'^show/?$'`, or `'^show$'`. Note the issue with the trailing slash. Is this a bug with the Inspector?

**Comment by GaryJones** [comment]
Can you please share what code registered that rewrite rule? And the URLs that were expected to work?

**Comment by lkraav** [comment]
It looks like I'm just bluntly doing

```php

    /**
     * Post format `video` slug, avoid mixing videos w/ `/blog/`
     *
     * @var string
     */
    public $wp_rewrite_front_post_format_video = 'show';

    add_action( 'init', function(): void {

        /**
         * @since 2018.03.01
         */
        add_rewrite_rule( '^' . $this->wp_rewrite_front_post_format_video . '/([^/]+)(?:/([0-9]+))?/?$', 'index.php?name=$matches[1]&page=$matches[2]' );
        add_rewrite_rule( '^' . $this->wp_rewrite_front_post_format_video . '/([^/]+)/amp(/(.*))?/?$', 'index.php?name=$matches[1]&amp=$matches[3]' );
        add_rewrite_rule( '^' . $this->wp_rewrite_front_post_format_video . '/page/([0-9]{1,})/?$', 'index.php?post_format=video&paged=$matches[1]', 'top' );
        add_rewrite_rule( '^' . $this->wp_rewrite_front_post_format_video . '/?$', 'index.php?post_format=video', 'top' );

    } );
```

**Comment by GaryJones** [comment]
I registered all four rewrite rules that you provided, and then added `/show/` to the matching URLs input field. The `^show/?$` rule is one of the matches, and the link at the top points to `http://localhost:10034/show/` (on my local environment):
<img width="1085" alt="Screenshot 2021-05-12 at 12 49 23" src="https://user-images.githubusercontent.com/88371/117970565-b4e27f00-b320-11eb-9013-244be47ea870.png">

When visiting that, I naturally got a 404, because I didn't have any posts with a `video` post format published.

After publishing, I landed on an archive of posts (just 1) with post format = video:

<img width="820" alt="Screenshot 2021-05-12 at 12 50 22" src="https://user-images.githubusercontent.com/88371/117970931-2cb0a980-b321-11eb-9246-23f4fb637c8c.png">

http://localhost:10034/show/page/1 also showed me the archive.

http://localhost:10034/show/page/2 showed my a 404, which is expected as I only have a single post format = video post published.

http://localhost:10034/show/video-post-format/ redirected to http://localhost:10034/video-post-format/ (likely through WP's canonical redirect).

Are you seeing different behaviour in the Rewrite Rules Inspector?

**Comment by GaryJones** [comment]
Closing for lack of feedback.
